loopt.py
markup_code.py
markup_trace.py
report.py
requirements.txt
resultt.py
runt.py
templates/link.jinja.html
templates/summary.jinja.html
templates/trace.jinja.html
tracet.py

This pull request fixes a number of mistakes.  Review this one commit at a time.
* Handle correctly name-mangled names of loops in static functions.
* Link correctly to loop unwinding assertion error traces.
* Allow the lists of loops and error traces to be empty.
* Manually escape characters rendered by jinja.
* Jinja trace template now correctly renders code snippets.
* Jinja templates no longer generate links to internal file names.

Corrections

---

README.md
filet.py
markup_trace.py
optionst.py
templates/summary.jinja.html
tracet.py

CBMC generates traces with builtin function calls visible and returns hidden.  This patch fixes this throwing away hidden steps in a trace, but retaining all function calls and returns to make trace rendering of  function calls work.  This is a temporary patch until https://github.com/diffblue/cbmc/issues/5413 is addressed.
This pull request also includes 4 other commits fixing small 5-line issues:
* Add installation tips to README.md
* Expand srcdir and wkdir args to absolute pathnames.
* Retain hidden function call/return pairs in traces
* Correct nested sorting in jinja summary template.
* Recognize *.log files as text files.

Retain hidden function call/return pairs

---

cbmc_viewer/templates/summary.jinja.html

This patch replaces the comma-separated shortcut `sort(attribute="attr1,attr2")` with the long form `sort(attribute="attr2")|sort(attribute="attr1")`. The shortcut used to work, but now fails with "No such attribute 'attr1,attr2'" in spite of the [sort documentation](https://jinja.palletsprojects.com/en/2.11.x/templates/#sort).

Fix jinja sorting of coverage results.

---

cbmc_viewer/symbol_table.py
cbmc_viewer/symbolt.py

Symbols are recorded in the symbol table with a mangled name and a pretty name.  Most cbmc output uses the pretty name, so modify the symbol table parser to use the pretty name for a symbol if it exists. 
Also clean up the symbol table parser to break the cbmc symbol table output into a sequence of definitions and then break each definition into a sequence of lines.  The prior implementation just scanned the cbmc output as a sequence of lines, which made grouping symbol names and locations ad hoc and error prone.

Improve symbol table parser

---

cbmc_viewer/coveraget.py

The MacOS header file `_ctype.h` contains inlined function
definitions, and cbmc coverage data can include coverage data for
these functions.  Since we don't generally care about coverage of
system code, and since we don't generally have easy access to source
code for system calls, we omit this code from the coverage
calculations.

Restrict coverage to source files under the source root.

---

cbmc_viewer/markup_trace.py
setup.py

First select the code snippet (eg, code up to the `;` ending the current statement) and then escape html characters (eg, replace `>` with `&gt;`).  Prior version escaped characters then selected the code snippet, truncating lines prematurely (eg, truncanting at `&gt;` or `>`

Fix code snippets, refresh pip setup.py

---

.github/workflows/create_tagged_release.py
.github/workflows/github_release.py
.github/workflows/release.yaml
.github/workflows/tagged_release_message.md

Write a github action triggered by pushing a tag of the form viewer-*, build a pip installation package, create a release page, and upload the package to the release page.

Add automation of package release

---

.gitignore
cbmc_viewer/markup_link.py
cbmc_viewer/srcloct.py
cbmc_viewer/tracet.py

It is possible for a source location to point to code outside of the
source tree (like an inlined function definition in a system header
file).  This patch replaces all such external source locations in
error traces with a special 'missing' source location, inhibiting
linking to external source code.

Strip external source locations from error traces.

---

cbmc_viewer/propertyt.py

Modify the voluptuous schema for the property object to allow the list of properties to be empty.

Allow property list to be empty

---

cbmc_viewer/markup_summary.py
cbmc_viewer/tracet.py

Silently skip loop-head steps in error traces: CBMC has added new kinds of steps to error traces, and the loop-head step is not interesting to us, so we silently skip over loop-head steps.
Correctly strip warning prefixes from warnings produced by CBMC: CBMC used to preface all warnings with the string "**** WARNING:" but CBMC now also uses "warning:".  This patch is more careful about what prefix it removes from warning messages.

Skip loop heads and strip warning prefixes

---

cbmc_viewer/symbol_table.py

Code with definitions like
```
static const char *UTF_16_BE_BOM = "\xFE\xFF";
```
will produce values in the symbol table that cannot read as strings of UTF-8 characters.  We read the symbol table using the latin1 encoding in place of the Python default UTF-8 encoding, since latin1 agrees with UTF-8 on the ASCII characters.

Read symbol table with latin1 character encoding.

---

cbmc_viewer/coveraget.py
cbmc_viewer/propertyt.py

Property names usually has the form file.function.integer, and property names are sorted using the key (file.function, integer).  Recursion unwinding properties sometimes have the form file.function.recursion.  This patch uses the sorting key (file.function.recursion, 0) for unusual property names like this.

Fix property sorting key

---

cbmc_viewer/srcloct.py

In a trace in the textual output of cbmc, the source location for an intrinsic function like the gcc atomic built-in functions may include only the function name and may omit the file name and line number.
This patch corrects the parsing of such source locations.

Correct the parsing of source locations in the textual output of cbmc.

---

.github/workflows/release.yaml

GitHub has modified of setting environment variable in workflows. This patch updates the workflow to use environment files in place of the deprecated set-env command.
For details, see
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Correct the setting of environment variables in GitHub Actions.

---

cbmc_viewer/markup_summary.py
cbmc_viewer/reachablet.py
cbmc_viewer/runt.py
cbmc_viewer/symbolt.py

The current implementation of the RMC model checker for Rust provides some incomplete information that viewer depends on .  This pull request makes a few changes to handle the missing information, mostly by providing placeholders for the data until it is produced.
This pull request also makes one change to reachable.py to handle a change in the json output of goto-analyzer.  It changes a key name from 'file name' to 'file' in the line 
```
file_name = function.get('file')
```

Extend CBMC Viewer to work with RBMC

---

cbmc_viewer/coveraget.py
cbmc_viewer/filet.py
cbmc_viewer/loopt.py
cbmc_viewer/markup_summary.py
cbmc_viewer/markup_trace.py
cbmc_viewer/propertyt.py
cbmc_viewer/reachablet.py
cbmc_viewer/resultt.py
cbmc_viewer/sourcet.py
cbmc_viewer/symbolt.py
cbmc_viewer/tracet.py

Pylint clean up.  Mostly the latest version of pylint started suggesting using the Python 3 style of subclassing (call super() without arguments, why did we not do this from the start) and suggesting the use of "raise from".

Run pylint

---

cbmc_viewer/coveraget.py

*Resolved issues:*
Issue #39 
Instead of splitting `FILE:FUNCTION:LINES` chunk on all colons, splits it only on the first and last colon, allowing the `FUNCTION` to contain colons safely. File names and line numbers can't contain colons, so this should be more robust.

Updated coverage parsing to allow functions with colons in name.

---

cbmc_viewer/markup_link.py
cbmc_viewer/srcloct.py

*Issue #45, if available:* 
Issue https://github.com/awslabs/aws-viewer-for-cbmc/issues/45
Viewer annotates only source files under SRCDIR, links steps of an
error trace only to lines of code in files under SRCDIR, and uses path
names relative to SRCDIR for files under SRCDIR.  With RMC, we see for
the first time errors triggered by lines of code in the RMC
implementation (eg, the Rust standard library) not under SRCDIR, and
viewer fails when it tries to generate a link to the line of code
triggering the error (in a library source file given by an absolute
path name).
With this commit, viewer will no longer try to link to a file specified
with an absolute path name (to a file not under SRCDIR).
By submitting this pull request, I confirm that you can use, modify, …

Don't link error traces to library source files

---

cbmc_viewer/markup_code.py
cbmc_viewer/markup_link.py

Currently when CBMC-viewer encounters a name like `<Sheep as Animal>::noise` (a Rust name), the angled brackets are treated as HTML tags, causing the name to be displayed incorrectly in viewer traces. This patch escapes HTML characters in the function names to avoid this issue in the future.

Escape function name to allow < and >

---

cbmc_viewer/symbol_table.py

This commit has the effect of doubling the number of C symbols since
the list now includes fully-qualified symbols like function::1::x that
denotes local variable x in scope 1 of function.  But this doesn't
change the html generated by viewer for C code.
Proposing this pull request in favor of https://github.com/awslabs/aws-viewer-for-cbmc/pull/42

Simplify symbol table parsing to work for both C and Rust

---

cbmc_viewer/markup_link.py

The source location for a global variable (a static variable) will
give a file name and a line number, but the function name will be
omitted (because there is no enclosing function to name).  Trying to
link a global variable to its source location will invoke markup
functions with text set to None (the missing function name).

Allow markup functions to return None when text to markup is None

---

summary/Makefile
summary/README.md
summary/projects.json
summary/stubs.py
summary/summary.py

This directory contains a script that scans the viewer output for a set of and produce a summary of the stubs and undefined functions being used in the proofs.  This is a work-in-progress, and will ultimately be incorporated into viewer and litani.

Add proof summary scripts (work in progress)

---

cbmc_viewer/templates.py

Set jinja to autoescape the content written to html via jinja templates.

Set jinja to autoescape html.

---

cbmc_viewer/tracet.py
tests/compare-result
tests/compare-trace

This pull request consists of three commits making three changes:
* Modifies the trace summary produced by make-trace on cbmc json output to more closely match the trace summary produced on cbmc json output 
* Adds a compare-trace command to compare two trace summaries (ignoring known discrepancies between cbmc json and xml output).
* Modifies the compare-result command to ignore a minor, known discrepancy between cbmc text and cbmc json/xml output.

Add compare-trace command

---

cbmc_viewer/coveraget.py
cbmc_viewer/srcloct.py

This pull request fixes the interpretation of basic block coverage descriptions.  The current implementation is correct only if all source locations contributing to a basic block come from the same file, but this is false when the basic block includes code inlined from multiple files.
Review this pull request commit by commit.  The commits are organized to make this easy.

Fix interpretation of basic block coverage descriptions

---

Makefile
setup.py

This commit causes 'make unpip' clean up completely after 'make pip', and causes 'make uninstall' clean up completely after 'make install'.

Better clean up for 'make unpip' and 'make uninstall'

---

cbmc_viewer/templates.py

I'm re-enabling the existing autoescaping of HTML for Jinja2 templates in a different way

fix: Re-enable Jinja2 autoescaping of HTML using a different way

---

README.md

This pull request adds an example showing how to used cbmc-viewer, and makes the installation instructions easier to read.  It is easier to read the formatted markdown with "view file" than it is to read the diff.

Add an example to README.md

---

src/cbmc_viewer/tracet.py

A prior commit added a visible_steps generator to modify which steps
in a trace are considered visible and to omit the remaining hidden
steps from the trace.  That commit incorrectly applied the generator
to the dict mapping trace names to traces, rather than to the traces
themselves.  This commit repairs that error.

Apply visible_steps to individual text traces

---

Makefile
README.md

This pull request renames the Makefile target pip -> build, and it adds a simple example of using cbmc-viewer to the top-level readme file (along with some language cleanups).

Add simple example to top-level readme file

---

Makefile
src/cbmc_viewer/configt.py
src/cbmc_viewer/coveraget.py
src/cbmc_viewer/loopt.py
src/cbmc_viewer/parse.py
src/cbmc_viewer/propertyt.py
src/cbmc_viewer/reachablet.py

This pull request reverts to loading xml file directly from the file instead of reading the file into a string and patching the string before parsing it.  The patch appears no longer to be needed since cbmc appears no longer to insert illegal characters into its xml output.  
This pull request also reverts to raising an exception when viewer can't load an xml or json file.
This pull request also cleans up some top-level Makefile targets.
This pull request should be read commit-by-commit, as the commits themselves are small and the commit messages explain what is going on.

Repair xml parsing

---

src/cbmc_viewer/reachablet.py

This pull request gets rid of a bogus ERROR message produced by malforned reachable function output for __CPROVER_Start

Skip malformed reachable function entry 

---

src/cbmc_viewer/resultt.py

When parsing multiple input files, shallow copies of EMPTY_RESULT cannot
be used for any file after the first one would end up modifying shared
data structures.

Result parsing: do not use shallow copies

---

.github/workflows/publish.yaml

Publish documentation via the documentation branch until it is ready to be merged into master.

Publish via documentation branch

---

tests/bin/difference.py

Strengthen the filter used by the regression script difference.py to
select the cbmc-viewer litani jobs.  Before this commit, the script
selected all jobs in the "report" pipeline. This commit strengthens
the filter used by difference.py to select only jobs in the "report"
pipeline with "cbmc-viewer" in the job command.

Modify regression script difference.py to select only cbmc-viewer jobs

---

Makefile
setup.cfg
src/cbmc_viewer/coveraget.py
src/cbmc_viewer/optionst.py
src/cbmc_viewer/resultt.py
src/cbmc_viewer/version.py
tests/bin/Makefile
tests/kani/.gitignore
tests/kani/Makefile
tests/kani/write_build_ninja.py

This pull request adds regression tests that run kani --visualize to test viewer on kani tests.
This pull request also does some minor cleanup, resets required python version back to 3.6 and advances version number to 3.2.

Kani regression

---

src/cbmc_viewer/ctagst.py
src/cbmc_viewer/runt.py
src/cbmc_viewer/symbolt.py

This pull request implements robust support for ctags.  This resolves https://github.com/model-checking/cbmc-viewer/issues/101.
Viewer adds to the symbol definitions found in the goto binary symbol table whatever symbol definitions ctags can find in the source files mentioned in the symbol table.  This adds, for example, definitions of type symbols.
There are three generations of ctags.  Universal ctags replaced exhuberant ctags replaced legacy ctags.  This code change invokes ctags using the universal API and then the exhuberant API and then the legacy API.  It uses the symbols returned by the first successful invocation, and continues without ctags symbols if no invocation is successful (for example, if ctags is not even installed).
This was tested on the HTTP proofs by running master …

Robust ctags

---

.github/workflows/ctags.yaml
setup.cfg
src/cbmc_viewer/ctagst.py
src/cbmc_viewer/symbolt.py
src/cbmc_viewer/version.py
tests/unit-tests/ctags/.gitignore
tests/unit-tests/ctags/Makefile
tests/unit-tests/ctags/symbol-exuberant.json
tests/unit-tests/ctags/symbol-legacy.json
tests/unit-tests/ctags/symbol-universal.json

This pull request extracts ctags support as a standalone module so it can be copied into other projects.  
Also modify ctags output to include the symbol kind (eg, "function").
Also advance version to 3.3

Extract ctags support as a stand-alone module

---

.github/workflows/release.yaml

Remove unwanted line breaks added by the last update to the release github workflow yaml file that appear in the formatted release page.

Repair release page line breaks

---

src/cbmc_viewer/ctagst.py

Resolves #122 
Replace the `text` parameter of `Popen` with `universal_newlines`, since `text` is only available in Python 3.7 and up (the default Python version on Ubuntu 18.04 is 3.6.8). The newer versions of Python still support `universal_newlines` for backward compatibility:
> New in version 3.7: text was added as a more readable alias for universal_newlines.
> The universal_newlines argument is equivalent to text and is provided for backwards compatibility.
Source: https://docs.python.org/3/library/subprocess.html#popen-constructor

Use universal_newlines to support older version of Python

---

.github/workflows/release-brew.yaml
tests/kani/Makefile

GitHub is planning to deprecate macOS 10.15 GitHub actions next month and is failing certain CI builds to raise awareness ([link](https://github.com/actions/virtual-environments/issues/5583))

Remove macOS 10.15 in GitHub Actions "build-bottle" job

---

setup.cfg

Required to satisfy the reqs of voluptuous 0.14.0 which now uses type annotations, a python 3.7+ feature.
Fixes #146 
Sets the minimum python version to 3.7.

Set minimum python version to 3.7

---

.github/workflows/release.yaml

Making github-bot user create the release would not trigger further actions (in our case we want brew and pypi release actions to be triggered).

Have release created by aws-viewer-for-cbmc-release-ci

---

.github/workflows/release-brew.yaml

More recent versions of upload-artifact refuse to upload/merge artifacts with the same name.

Avoid name clash when uploading artifacts from multiple platforms

---

.github/workflows/release-brew.yaml
.github/workflows/release-pypi.yaml

This is deprecated since October 2022.

CI jobs: remove use of deprecated set-output

---

.github/workflows/release-brew.yaml

Earlier steps already depend on jq.

Do not unnecessarily re-install jq

---

.github/workflows/release-brew.yaml

Fixes the output name to match the variable name that was changed in fbf6eca0. (The change in fbf6eca0 was unintentional, but makes it more uniform with other output names.)

fixup! CI jobs: remove use of deprecated set-output

---

.github/workflows/release-brew.yaml

This is an attempt to also have update-pr use a personal-access token - the build-bottle jobs use the very same steps to access secretsmanager and seem to be able to use the resulting token.

Extend permissions to make update-pr work

---

.github/workflows/release-brew.yaml

Try to use exactly the same steps as the preceding task.

Second attempt to fix update-pr

---

.github/workflows/release-brew.yaml

We cannot rely on values in GITHUB_ENV that were stored earlier in the same step. Instead, directly query secretsmanager as needed.
Also fixes the committer-email that used the literal `BOT_EMAIL` string rather than the variable.

Fix update-pr workflow

---

src/cbmc_viewer/parse.py

Parsing CBMC's results in a memory consumption that is 100 times the size of the input file. Switching to cElementTree appears to halve the memory footprint, which can make the difference as to whether this fits into host memory. We could reduce the memory footprint a lot by iterating (and cleaning up) over the input XML nodes, but this requires a much larger re-architecting of the source.

Use cElementTree to reduce memory consumption

---

src/cbmc_viewer/resultt.py

The HTML rendering of property failures should not include (broken) links to counterexample traces the property status of which is "UNKNOWN".

Do not produce trace links for UNKNOWN status

---

.github/workflows/release-brew.yaml
.github/workflows/release-pypi.yaml

upload-release-asset is long deprecated.

Use action-gh-release to replace deprecated upload-release-asset

---

.github/workflows/release-pypi.yaml

See https://docs.pypi.org/trusted-publishers/using-a-publisher/ and https://github.com/pypa/gh-action-pypi-publish. This avoids the need for an upload token after having configured our GitHub action as trusted publisher in our PyPi account.
All API tokens have been removed from the account.

Use trusted publisher with PyPi and blessed action

---

.github/workflows/release-pypi.yaml
.github/workflows/release.yaml
.github/workflows/run-differential-tests.yaml

This has been deprecated by GitHub for its (free) security support has expired.

Do not use Ubuntu 20.04 in CI

---

src/cbmc_viewer/tracet.py

Some CBMC solvers like CVC5 can generate a cbmc.xml file containing failed verification results but without the failure trace (or a goto_trace field). With the current behavior, cbmc_viewer will crash when invoked because line 353 will try to iterate through None. This commit fixes this bug.
Here is a sample XML file that triggers this crash
<?xml version="1.0" encoding="UTF-8"?>
<cprover>
<program>CBMC 6.3.1 (cbmc-6.3.1)</program>
<message type="STATUS-MESSAGE">
<text>CBMC version 6.3.1 (cbmc-6.3.1) 64-bit x86_64 linux</text>
</message>
...
<message type="STATUS-MESSAGE">
<text>Running SMT2 ALL (with FPA) using CVC5</text>
</message>
<message type="STATUS-MESSAGE">
<text>Runtime Solver: 0.00640582s</text>
</message>
<message …

Support XML files containing failed results but no goto_trace field.

---

.github/workflows/release-brew.yaml

`brew test-bot` eventually walks all formulae to determine what might depend on cbmc-viewer, thereby walking into what appears to be a broken formula at `hashicorp/tap/vagrant`. This tap is entirely unrelated and also unnecessary for our purposes, so just remove it.

Brew untap hashicorp
