model-checking/cbmc-viewer

- markup_code.py
The goto symbol table sometimes refers to files that are part of the
CBMC implementation (eg, gcc_builtin_headers_types.h) and not
available for source code annotation.  This patch adds exception
handling (try/except) to deal with missing "source files" listed in
the symbol table.
> Skip annotation of the "source files" in the CBMC implementation.

- cbmc_viewer/markup_link.py
> Replace assertion failure with UserWarning exception.

- cbmc_viewer/tracet.py
This pull request makes three simple changes to support debugging error traces summarized by cbmc viewer under visual studio code.
> Visual Studio Code variable support

- cbmc_viewer/version.py
Signed-off-by: Felipe R. Monteiro <felisous@amazon.com>
N/A.
Fix version number.
> Fix version number (v2.5)

- cbmc_viewer/version.py
- setup.py
Advance version number to 2.6.
> Advance version to 2.6.

- cbmc_viewer/version.py
- setup.py
> Advance version to 2.7

- Makefile
- cbmc_viewer/optionst.py
- cbmc_viewer/resultt.py
- cbmc_viewer/srcloct.py
- cbmc_viewer/tracet.py
- cbmc_viewer/viewer.py
This is a collection of modifications to make viewer work better with function contract checking.  This is most easy to review commit-by-commit.
> Contract modifications

- cbmc_viewer/version.py
- setup.py
> Advance version to 2.8

- .github/workflows/tagged_release_message.md
- Makefile
- README.md
Update documentation and release pages.
> Update documentation and release page

- cbmc_viewer/version.py
- setup.py
> Advance viewer to version 2.9

- .github/workflows/tagged_release_message.md
Fix line breaks in release message for next release.
> Fix line breaks in release message for next release.

- cbmc_viewer/tracet.py
CBMC marks some steps in a trace as hidden.  Before this commit, viewer made visible all hidden function invocations, function returns, and variable assignments.  These hidden variable assignments included some assignments to variables internal to CBMC.  With this commit, viewer makes visible only those variable assignments that initialize static data.
> Add a generator for the visible steps appearing in a trace.

- cbmc_viewer/version.py
- setup.py
> Advance version to 2.10

- tests/unit-tests/visible-steps/Makefile
- tests/unit-tests/visible-steps/README.md
- tests/unit-tests/visible-steps/main.c
- tests/unit-tests/visible-steps/viewer-trace.json
This pull request adds a unit test illustrating the fix in https://github.com/awslabs/aws-viewer-for-cbmc/pull/76
> Add the visible-steps unit test

- .github/workflows/bump-brew-formula.yaml
- .github/workflows/tagged_release_message.md
> Add bump-brew-formula workflow

- .github/workflows/release.yaml
> Update release token

- setup.cfg
- src/cbmc_viewer/version.py
> Advance version to 2.11

- .github/workflows/release.yaml
> Fix release notes

- setup.cfg
- src/cbmc_viewer/version.py
Advance version to 2.12, and change github url to model-checking organization.
> Advance version to 2.12

- .github/workflows/run-differential-tests.yaml
> Clean up test workflow

- .github/workflows/release-pypi.yaml
> Upload wheel package to release

- setup.cfg
- src/cbmc_viewer/version.py
- tests/repo-tests/coreHTTP/bug.patch
> Advance version to 2.13

- .github/workflows/release-brew.yaml
> Force creation of PR to aws/tap to bump formula

- setup.cfg
- src/cbmc_viewer/version.py
> Advance version to 2.14

- .github/workflows/run-differential-tests.yaml
> Test changes on different python versions

- setup.cfg
- src/cbmc_viewer/cbmc_viewer.py
- src/cbmc_viewer/etc/bash_completion.d/cbmc-viewer.sh
Adds bash completion for viewer command line options.
> Add bash completion

- setup.cfg
- src/cbmc_viewer/version.py
- src/cbmc_viewer/viewer.py
Advancing major version since command interface has changes (make-* utility functions are now subcommands of cbmc-viewer).
> Advance version to 3.0

- setup.cfg
- src/cbmc_viewer/version.py
> Advance version to 3.0.1

- .github/workflows/release.yaml
- README.md
This code change improves/modernizes the installation instructions on the top-level README and the release page.
This resolves https://github.com/model-checking/cbmc-viewer/issues/38
> Improve installation instructions

- setup.cfg
- src/cbmc_viewer/version.py
> Advance version to 3.4

- setup.cfg
- src/cbmc_viewer/version.py
> Advance version to 3.5

- setup.cfg
- src/cbmc_viewer/version.py
> Advance version to 3.6

- src/cbmc_viewer/coveraget.py
This patch modifies viewer to skip and log malformed coverage data found in cbmc coverage output, and to log a message to the console warning the user that coverage data has been skipped and coverage results may not be correct:
```
WARNING: Skipping malformed coverage data in coverage.xml.
WARNING: Use the --verbose to see what coverage data was skipped.
```
For a source location without a function name, the verbose flag produces
```
INFO: Skipping malformed source location in coverage goal: Found file:file.c function: line:72
INFO: Skipping malformed source location in coverage goal description: block 1 (lines file.c::72): Found file:file.c function: line:72
```  
Review this pull request commit-by-commit to make the changes easy to see and understand.
Resolves …
> Skip malformed coverage data

- setup.cfg
- src/cbmc_viewer/version.py
Advance version from 3.6 to 3.7.
> Advance version to 3.7

- .github/workflows/release-brew.yaml
- .github/workflows/run-differential-tests.yaml
Replacing pull request https://github.com/model-checking/cbmc-viewer/pull/130
> Update brew release to run on macos

- setup.cfg
- src/cbmc_viewer/propertyt.py
- src/cbmc_viewer/tracet.py
- src/cbmc_viewer/version.py
See individual commit messages for details.
> CBMC v6 fixes and release 3.9

- .github/cloudformation/README.md
- .github/cloudformation/oidc.yaml
- .github/cloudformation/token.yaml
- .github/workflows/release-brew.yaml
- .github/workflows/release-pypi.yaml
- .github/workflows/release.yaml
We no longer have non-rotating secrets stored in the repository configuration. Implementation copied and adapted from proof-debugger.
> Fetch access tokens from AWS Secrets Manager

- .github/workflows/release-brew.yaml
- .github/workflows/release-pypi.yaml
- .github/workflows/release.yaml
See https://github.com/aws-actions/configure-aws-credentials and also how proof-debugger does it.
> Fix permissions to enable configure-aws-credentials

- .github/dependabot.yml
This will help keep up-to-date any actions that we use.
> Add Dependabot for GitHub action updates

- .github/workflows/release-brew.yaml
- .github/workflows/release-pypi.yaml
- .github/workflows/release.yaml
Use GitHub's log masking to ensure even tokens that do not match GitHub's default filter are replaced by asterisks.
> Make sure no information fetched from secrets manager is logged

- setup.cfg
- src/cbmc_viewer/version.py
> Advance version to 3.10

- src/cbmc_viewer/markup_code.py
- src/cbmc_viewer/symbol_table.py
Supersedes https://github.com/model-checking/cbmc-viewer/pull/185
> Turn warning into info.

- setup.cfg
- src/cbmc_viewer/version.py
> Advance version to 3.11
